### ISSUE TITLE
DB Extractors Configurations Migration

### ISSUE THREAD

**Issue by MiroCillik** [keboola/config-migration-tool#1]
Tento nastroj sa moze casom pouzit aj na migraciu dalsich komponent, ale ako prve zmigrujeme konfiguracie DB extraktorov, respektive konfiguracie db-extractor-bundle (ex-db).

Predstava ja taka, ze uzivatel si v UI klikne, ze chce zmigrovat svoje konfiguracie. Spusti sa job tejto komponenty a ten pre kazdu povodnu konfiguraciu v SYS buckete zalozi novu konfiguraciu cez SAPI configuration API.

Staru konfiguraciu v SYS bucketoch preistotu necha ako je.

**Comment by Halama** [comment]
jo to zní dobře
