### ISSUE TITLE
don't migrate adwords authorization part

### ISSUE THREAD

**Issue by kacurez** [keboola/config-migration-tool#17]
Ked sa migruje adwords na novu komponentu tak v konfigu zkopiruje auhtorization property ktorej credentials ukazuju na credentials oauthu starej komponenty a to rozbije ui ktore ich ocakava ale nevie ich z oauth-v2 nacitat pretoze tam niesu.

**Comment by JakubMatejka** [comment]
Fixed by 1.8.1
