### ISSUE TITLE
Multi region support

### ISSUE THREAD

**Issue by Halama** [keboola/config-migration-tool#19]
There are hardcoded URLs in current version https://github.com/keboola/config-migration-tool/blob/98a8bd9d3d74298e67a32a3c9f9dfa7e9e601441/src/Keboola/ConfigMigrationTool/Service/StorageApiService.php#L85 so it won't work in other KBC stacks.

**Comment by odinuv** [comment]
fixed in 9824decfe0221ebd02ea794a8bc965d88f937859
