### ISSUE TITLE
migration with data encryption

### ISSUE THREAD

**Issue by kacurez** [keboola/config-migration-tool#2]
1. Zavola POST na kbc create-config s configId, name, a description, polozka configuration bude prazdna
http://docs.keboola.apiary.io/#reference/component-configurations/component-configs/create-config
2. Vsetky property kt sa maju zasifrovat sa ohashuju, tj `"password": "abc"` -> `"#password": "abc"`
3. Zavola PUT na docker save&encrypt config s configuration parametrom(form-data)
http://docs.kebooladocker.apiary.io/#reference/encrypt/encrypt-and-store-configuration/save-configuration

**Comment by MiroCillik** [comment]
ok, diky, implementovane
