### ISSUE TITLE
AdWords Oauth External not working after migration

### ISSUE THREAD

**Issue by MiroCillik** [keboola/config-migration-tool#23]
"Po migraci oauth komponenty (adwords) failuje externí autorizace: https://external.keboola.com/oauth/index.html?token=313-141942-fa72f1080847aac0b628e551c0793660b80bcd25&sapiUrl=https://connection.keboola.com#/keboola.ex-google-adwords-reports-v201802/386870895 v logu najdu `oauth-v2-86a6c11199404e9dc5f6ea16eb0e28c7` a “No data found for api: keboola.ex-google-adwords-reports-v201802 with id: 386870895 in project [dev] Jakub”. Když přitom vytvořím novou konfiguraci, tak k téhle chybě nedojde."

**Comment by MiroCillik** [comment]
Possible duplicate of https://github.com/keboola/config-migration-tool/issues/17

**Comment by JakubMatejka** [comment]
Fixed by 1.8.1

**Comment by JakubMatejka** [comment]
Hm, tak to nepomohlo ;o( (https://connection.keboola.com/admin/projects/313/extractors/keboola.ex-google-adwords-reports-v201802/386870895)

**Comment by JakubMatejka** [comment]
Sorry, nějak mi nedošlo, že se to musí znovu zmigrovat. ;o)) Funguje to ok
