### ISSUE TITLE
Mazat zmigrované konfigurace? 

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/config-migration-tool#25]
Při postupným migrování Adwords už tam mají někteří klienti i čtyři zmigrovaný verze od každý konfigurace a ty starý stejně nejdou spustit (protože dostanou do konfigurace `migrationStatus` a na tom spadne nějaká ta validace parametrů)

**Comment by odinuv** [comment]
https://keboola.slack.com/archives/C02C3GZUS/p1527583397000193

**Comment by MiroCillik** [comment]
Riesi sa v https://github.com/keboola/config-migration-tool/issues/26
