### ISSUE TITLE
migrace google analytics

### ISSUE THREAD

**Issue by kacurez** [keboola/config-migration-tool#5]
trocha som nad tym dumal tak to pisem aby mi to nevypadlo z hlavy, ked tak upravte tento koment pre kompletnejsi popis..
**`custom query run v orchestraciach`**  - sucasny(stary) ex-ga umoznuje pustit extrakci s parametrami: `since, until, dataset, config`, vsimol som si ze APD to hodne vyuziva v orchestracich. Docker udajne umoznuje mergovat `configData` s `config` tj pustim run s configData aj config parametrom a docker to co je v configData domerguje do ulozeneho configu. Treba otestovat

**Comment by odinuv** [comment]
aha, no soucasny docker to nezmerguje, ale task parameters v orchestracich se bude stejne rusit prece
