### ISSUE TITLE
BigQuery Writer - json-mode after migration

### ISSUE THREAD

**Issue by Halama** [keboola/config-migration-tool#69]
Pokud zmigruji konfiguraci ze starého BigQuery Extractoru na nový tak se nová konfigurace přepne do JSON režimu a není možné tím pádem ji autorizovat dále.

Zendesk: https://keboola.zendesk.com/agent/tickets/10329
![image](https://user-images.githubusercontent.com/903531/56577878-727c6700-65cc-11e9-954a-6a2873921f5a.png)

**Comment by ondrejhlavacek** [comment]
UI by na tohle mělo bejt odolný, to je divný.

**Comment by ondrejhlavacek** [comment]
Večer bych na to mrknul, service account může bejt úplně chybět stejně jako u novejch konfigurací.

**Comment by ondrejhlavacek** [comment]
Ne, tak máte pravdu, UI by to sice mohlo umět, ale neumí a upravovat to teď nebudu, to by mohl bejt docela overkill, upravím tu migraci.

**Comment by ErikZigo** [comment]
No ja se do te migrace chtel odpoledne pustit, ale tys mi to vytrhl :-) Tak jestli budes radeji menit vecer plynky tak to muzu udelat.

**Comment by ondrejhlavacek** [comment]
@ErikZigo ještě jsou v porodnici, takže večer klid :-)

**Comment by ondrejhlavacek** [comment]
vyzkoušeno, je to fixnutý
